"""Pre-commit hook: check public API docstrings.

Walks the platform's ``apps/`` tree and flags every public function,
async function, and class that is missing a docstring. The check is
intentionally strict: it runs in CI but can be relaxed locally via the
``--tier`` argument.

The output is a list of ``file:line - name missing docstring`` entries
suitable for grepping in CI logs. Exit code is non-zero when at least
one missing docstring is found.

Usage::

    python scripts/check_docstrings.py
    python scripts/check_docstrings.py --tier services  # only services.py
    python scripts/check_docstrings.py --baseline 50    # allow up to 50 misses
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
APPS = BACKEND / "apps"


def _is_public(name: str) -> bool:
    """A name is public if it does not start with ``_`` and is not a dunder."""
    if name.startswith("_") and not (name.startswith("__") and name.endswith("__")):
        return False
    return True


def _should_skip(path: Path) -> bool:
    """Skip generated, test, and migration files."""
    parts = path.parts
    if "migrations" in parts or "tests" in parts:
        return True
    if path.name in {"manifest.py", "health.py"}:
        # Auto-generated by R-02 / R-01; docs are inline in the factory.
        return True
    return False


def _iter_targets(tree: ast.AST):
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if _is_public(node.name):
                yield node


def check_file(path: Path) -> list[str]:
    issues: list[str] = []
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return [f"{path}:1 - syntax error: {exc.msg}"]
    for node in _iter_targets(tree):
        if not ast.get_docstring(node):
            kind = "class" if isinstance(node, ast.ClassDef) else "def"
            issues.append(f"{path}:{node.lineno} - {kind} {node.name}()")
    return issues


def main() -> int:
    parser = argparse.ArgumentParser(description="Check public API docstrings")
    parser.add_argument(
        "--tier",
        choices=["all", "services", "views", "models"],
        default="all",
        help="Restrict the check to a subset of files",
    )
    parser.add_argument(
        "--baseline",
        type=int,
        default=0,
        help="Allow up to N missing docstrings (for incremental adoption)",
    )
    args = parser.parse_args()

    tiers: dict[str, str] = {
        "services": "services.py",
        "views": "views.py",
        "models": "models.py",
        "all": "",
    }
    suffix = tiers[args.tier]

    all_issues: list[str] = []
    for py_file in APPS.rglob("*.py"):
        if _should_skip(py_file):
            continue
        if suffix and not py_file.name.endswith(suffix):
            continue
        all_issues.extend(check_file(py_file))

    if len(all_issues) > args.baseline:
        print(f"\n{len(all_issues)} public APIs missing docstrings (baseline={args.baseline}):")
        for issue in all_issues:
            print(f"  {issue}")
        return 1

    print(
        f"OK: {len(all_issues)} public APIs missing docstrings "
        f"(within baseline={args.baseline})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
