# Generated by Django 5.2 on 2026-08-25 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('industry', models.CharField(choices=[('restaurants_cafes', 'Restaurants and Cafes'), ('retail', 'Retail'), ('logistics', 'Logistics'), ('other', 'Other')], default='other', max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('read_only', 'Read Only'), ('pending_deletion', 'Pending Deletion'), ('deleted', 'Deleted')], default='trial', max_length=32)),
                ('trial_started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField()),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('read_only_until', models.DateTimeField(blank=True, null=True)),
                ('deletion_due_at', models.DateTimeField(blank=True, null=True)),
                ('logo_name', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(blank=True, max_length=32)),
                ('secondary_color', models.CharField(blank=True, max_length=32)),
                ('accent_color', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms', 'Terms of Use'), ('privacy', 'Privacy Notice'), ('ai_transfer', 'AI Transfer Notice'), ('employee_privacy', 'Employee Privacy Acknowledgement')], max_length=32)),
                ('document_version', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to='tenancy.company')),
            ],
        ),
        migrations.CreateModel(
            name='SupportAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_authorizations', to='tenancy.company')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_grants', to=settings.AUTH_USER_MODEL)),
                ('support_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'trial_ends_at'], name='tenancy_com_status_a53c52_idx'),
        ),
        migrations.AddIndex(
            model_name='legalacceptance',
            index=models.Index(fields=['company', 'document_type', 'document_version'], name='tenancy_leg_company_ee807b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportauthorization',
            index=models.Index(fields=['company', 'active'], name='tenancy_sup_company_ec90f9_idx'),
        ),
    ]
