# Generated by Django 5.2 on 2026-08-26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportauthorization",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supportauthorization",
            name="reason",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="supportauthorization",
            index=models.Index(fields=["active", "expires_at"], name="tenancy_sup_active_6a38a7_idx"),
        ),
    ]
