# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_supportauthorization_expiry"),
    ]

    operations = [
        migrations.DeleteModel(name="SupportAuthorization"),
    ]
