# Generated by Django 5.2.17 on 2026-08-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_remove_support_authorization'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='tenancy_com_status_a53c52_idx',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deletion_due_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='read_only_until',
        ),
        migrations.RemoveField(
            model_name='company',
            name='trial_ends_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='trial_started_at',
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=32),
        ),
    ]
