# Generated by Django 5.2.17 on 2026-09-04

from django.db import migrations, models
from django.utils import timezone


def seed_installation_state(apps, schema_editor):
    InstallationState = apps.get_model("tenancy", "InstallationState")
    Company = apps.get_model("tenancy", "Company")
    InstallationState.objects.get_or_create(
        id=1,
        defaults={"configured_at": timezone.now() if Company.objects.exists() else None},
    )


class Migration(migrations.Migration):
    dependencies = [("tenancy", "0004_remove_company_tenancy_com_status_a53c52_idx_and_more")]

    operations = [
        migrations.CreateModel(
            name="InstallationState",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("configured_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(seed_installation_state, migrations.RunPython.noop),
    ]
