# Generated by Django 5.2.17 on 2026-08-26 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='completed', max_length=32)),
                ('shadow_mode', models.BooleanField(default=True)),
                ('auto_pass_eligible', models.BooleanField(default=False)),
                ('auto_pass_activated', models.BooleanField(default=False)),
                ('risk_level', models.CharField(blank=True, max_length=32)),
                ('provider_payload', models.JSONField(default=dict)),
                ('provider_result', models.JSONField(default=dict)),
                ('human_decision', models.CharField(blank=True, max_length=32)),
                ('agreement_with_human', models.BooleanField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_runs', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_runs', to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('evidence_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_runs', to='evidence.evidenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(default='fake', max_length=64)),
                ('endpoint_url', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('credential_reference', models.CharField(blank=True, max_length=255)),
                ('monthly_token_limit', models.PositiveIntegerField(default=10000)),
                ('monthly_cost_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_config', to='tenancy.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_provider_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysisCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('criteria_json', models.JSONField(default=dict)),
                ('reference_media_names', models.JSONField(default=list)),
                ('shadow_mode', models.BooleanField(default=True)),
                ('auto_pass_enabled', models.BooleanField(default=False)),
                ('auto_pass_risk_threshold', models.PositiveSmallIntegerField(default=70)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_criteria', to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_analysis_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'version_number'), name='ai_analysis_criteria_version_unique')],
            },
        ),
    ]
