# Generated by Codex on 2026-08-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_supportauthorization_expiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentGrant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=160)),
                ("client_fingerprint", models.CharField(max_length=128)),
                ("scopes", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("active", "Active"), ("revoked", "Revoked"), ("expired", "Expired")], default="active", max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_grants", to="tenancy.company")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_grants", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="AgentActionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("request_id", models.UUIDField(db_index=True)),
                ("tool_name", models.CharField(max_length=160)),
                ("required_scope", models.CharField(max_length=96)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("arguments_hash", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("received", "Received"), ("executed", "Executed"), ("rejected", "Rejected"), ("failed", "Failed")], default="received", max_length=32)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=96)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_action_logs", to="tenancy.company")),
                ("grant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="action_logs", to="agent_access.agentgrant")),
            ],
        ),
        migrations.CreateModel(
            name="AgentPendingAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("executing", "Executing"), ("executed", "Executed"), ("rejected", "Rejected"), ("expired", "Expired"), ("cancelled", "Cancelled"), ("superseded", "Superseded"), ("failed", "Failed")], default="pending", max_length=32)),
                ("action_type", models.CharField(max_length=160)),
                ("payload", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("terminal_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_log", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="pending_actions", to="agent_access.agentactionlog")),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="agent_pending_action_decisions", to=settings.AUTH_USER_MODEL)),
                ("grant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pending_actions", to="agent_access.agentgrant")),
            ],
        ),
        migrations.AddIndex(
            model_name="agentgrant",
            index=models.Index(fields=["company", "status"], name="agent_acces_company_7a8689_idx"),
        ),
        migrations.AddIndex(
            model_name="agentgrant",
            index=models.Index(fields=["client_fingerprint", "status"], name="agent_acces_client__ad8230_idx"),
        ),
        migrations.AddIndex(
            model_name="agentactionlog",
            index=models.Index(fields=["company", "created_at"], name="agent_acces_company_fa1e7b_idx"),
        ),
        migrations.AddIndex(
            model_name="agentactionlog",
            index=models.Index(fields=["tool_name", "status"], name="agent_acces_tool_na_e29e38_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentactionlog",
            constraint=models.UniqueConstraint(fields=("grant", "tool_name", "idempotency_key"), name="agent_action_unique_idempotency_key"),
        ),
        migrations.AddIndex(
            model_name="agentpendingaction",
            index=models.Index(fields=["grant", "status"], name="agent_acces_grant_i_afa6c4_idx"),
        ),
        migrations.AddIndex(
            model_name="agentpendingaction",
            index=models.Index(fields=["expires_at", "status"], name="agent_acces_expires_0e5d2a_idx"),
        ),
    ]
