# Generated by Django 5.2 on 2026-08-25 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('number', 'Number'), ('note', 'Note'), ('confirmation', 'Confirmation')], max_length=32)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('challenge_text', models.CharField(blank=True, max_length=255)),
                ('challenge_answer', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_sessions', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_sessions', to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capture_sessions', to=settings.AUTH_USER_MODEL)),
                ('task_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_sessions', to='tasks.taskinstance')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capture_sessions', to='tasks.tasktemplateversion')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_capture_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskIssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('photo_name', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_issue_reports', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_issue_reports', to='tenancy.company')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_issue_reports', to=settings.AUTH_USER_MODEL)),
                ('task_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='tasks.taskinstance')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDiscussionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_discussion_messages', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_discussion_messages', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_discussion_messages', to='tenancy.company')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='evidence.taskdiscussionmessage')),
                ('task_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='tasks.taskinstance')),
                ('issue_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='evidence.taskissuereport')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('number', 'Number'), ('note', 'Note'), ('confirmation', 'Confirmation')], max_length=32)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected')], default='submitted', max_length=32)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('note_text', models.TextField(blank=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirmation_value', models.BooleanField(blank=True, null=True)),
                ('quarantine_name', models.CharField(blank=True, max_length=255)),
                ('private_media_name', models.CharField(blank=True, max_length=255)),
                ('blurred_media_name', models.CharField(blank=True, max_length=255)),
                ('media_mime_type', models.CharField(blank=True, max_length=120)),
                ('media_size_bytes', models.PositiveIntegerField(default=0)),
                ('media_width', models.PositiveIntegerField(blank=True, null=True)),
                ('media_height', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_hash', models.CharField(blank=True, max_length=64)),
                ('derivative_hash', models.CharField(blank=True, max_length=64)),
                ('duplicate_risk_score', models.PositiveSmallIntegerField(default=0)),
                ('face_detected', models.BooleanField(default=False)),
                ('challenge_response', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='organizations.branch')),
                ('capture_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='evidence.capturesession')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='tenancy.company')),
                ('parent_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='evidence.evidenceitem')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to=settings.AUTH_USER_MODEL)),
                ('task_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='tasks.taskinstance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('capture_session',), name='evidence_one_item_per_session'), models.UniqueConstraint(fields=('task_instance', 'sequence_number'), name='evidence_sequence_unique_per_task')],
            },
        ),
    ]
