# Generated by Django 5.2 on 2026-08-25 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=96)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignment_mode', models.CharField(choices=[('named_user', 'Named User'), ('role_pool', 'Role Pool'), ('monitor_distributed', 'Monitor Distributed')], max_length=32)),
                ('assigned_role_code', models.CharField(blank=True, max_length=64)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=32)),
                ('task_weight', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_task_templates', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='tenancy.company')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurrence_type', models.CharField(choices=[('daily_fixed', 'Daily Fixed'), ('weekly_fixed', 'Weekly Fixed'), ('shift_relative', 'Shift Relative')], max_length=32)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shift_offset_minutes', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_schedules', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_schedules', to='tenancy.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.tasktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('instructions', models.TextField()),
                ('checklist_definition', models.JSONField(default=list)),
                ('evidence_requirements', models.JSONField(default=list)),
                ('reference_instructions', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tasks.tasktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_instances', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instances', to='organizations.branch')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_task_instances', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instances', to='tenancy.company')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='tasks.taskschedule')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tasks.tasktemplate')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tasks.tasktemplateversion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_transfer_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_transfer_targets', to=settings.AUTH_USER_MODEL)),
                ('task_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='tasks.taskinstance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='tasks_template_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='taskschedule',
            constraint=models.UniqueConstraint(fields=('company', 'template', 'branch', 'recurrence_type', 'weekday', 'scheduled_time'), name='tasks_schedule_unique'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='tasks_template_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_for'), name='tasks_instance_schedule_unique'),
        ),
    ]
