# Generated by Django 5.2.17 on 2026-09-25 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_multi_branch_assignments'),
        ('tasks', '0002_taskrequest'),
        ('tenancy', '0005_installationstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['company', 'status', 'due_at'], name='tasks_inst_co_stat_due_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['schedule', 'status'], name='tasks_inst_sched_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['branch', 'status', 'due_at'], name='tasks_inst_br_stat_due_idx'),
        ),
    ]
