# Generated by Django 5.2.17 on 2026-09-29 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_multi_branch_assignments'),
        ('tasks', '0003_taskinstance_tasks_inst_co_stat_due_idx_and_more'),
        ('tenancy', '0005_installationstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__gte', models.F('started_at'))), name='tasks_instance_completed_after_started'),
        ),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__gte', models.F('scheduled_for'))), name='tasks_instance_due_after_scheduled'),
        ),
    ]
