#!/usr/bin/env python3
"""Prepare a native Mhami installation on Linux or Windows.

The bootstrapper deliberately does not install operating-system packages or
write service definitions. Those operations require platform-specific
privileges and are handled by the companion scripts after this step.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import secrets
import socket
import subprocess
import sys
from pathlib import Path


def _secret() -> str:
    return secrets.token_urlsafe(48)


def _fernet_key() -> str:
    from cryptography.fernet import Fernet

    return Fernet.generate_key().decode("ascii")


def _external_key() -> str:
    return base64.urlsafe_b64encode(os.urandom(32)).decode("ascii")


def _prompt(value: str | None, label: str, default: str = "") -> str:
    if value is not None:
        return value
    suffix = f" [{default}]" if default else ""
    answer = input(f"{label}{suffix}: ").strip()
    return answer or default


def _write_env(path: Path, values: dict[str, str], *, force: bool) -> None:
    if path.exists() and not force:
        raise RuntimeError(f"Refusing to overwrite existing environment file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by Mhami native installer. Protect this file as a secret.\n"
        + "".join(f"{key}={value}\n" for key, value in values.items()),
        encoding="utf-8",
    )
    if os.name != "nt":
        path.chmod(0o640)
    else:
        try:
            subprocess.run(
                [
                    "icacls",
                    str(path),
                    "/inheritance:r",
                    "/grant:r",
                    "SYSTEM:F",
                    "Administrators:F",
                ],
                check=True,
                capture_output=True,
                text=True,
            )
        except (OSError, subprocess.CalledProcessError) as exc:
            raise RuntimeError(f"Failed to protect Windows environment file: {path}") from exc


def build_values(args: argparse.Namespace) -> dict[str, str]:
    hostname = _prompt(args.hostname, "Public hostname", "localhost" if args.mode == "standalone" else socket.getfqdn())
    backup_uri = _prompt(args.backup_external_uri, "External backup URI", "")
    if not backup_uri:
        raise ValueError("An approved external backup URI is required for production mode.")
    if args.mode == "standalone" and hostname in {"", "0.0.0.0"}:
        hostname = "localhost"
    return {
        "DJANGO_SETTINGS_MODULE": "config.settings.prod",
        "DJANGO_DEBUG": "false",
        "DJANGO_SECRET_KEY": _secret(),
        "DJANGO_ALLOWED_HOSTS": hostname,
        "AUDIT_HMAC_SECRET": _secret(),
        "MCP_INTERNAL_HMAC_SECRET": _secret(),
        "MFA_ENCRYPTION_KEYS": _fernet_key(),
        "POSTGRES_DB": args.postgres_db,
        "POSTGRES_USER": args.postgres_user,
        "POSTGRES_PASSWORD": args.postgres_password or _secret(),
        "POSTGRES_HOST": args.postgres_host,
        "POSTGRES_PORT": str(args.postgres_port),
        "REDIS_URL": args.redis_url,
        "CACHE_URL": args.redis_url.replace("/0", "/2"),
        "CELERY_RESULT_BACKEND": args.redis_url.replace("/0", "/1"),
        "MEDIA_ROOT": str(args.data_root / "media"),
        "STATIC_ROOT": str(args.data_root / "static"),
        "BACKUP_STORAGE_ROOT": str(args.data_root / "backups"),
        "BACKUP_RESTORE_ROOT": str(args.data_root / "backup-restores"),
        "BACKUP_ENCRYPTION_KEY": _fernet_key(),
        "METRICS_TOKEN": _secret(),
        "BACKUP_EXTERNAL_URI": backup_uri,
        "BACKUP_EXTERNAL_KEY_ID": "primary",
        "BACKUP_EXTERNAL_KEYS": json.dumps({"primary": _external_key()}),
        "GUNICORN_WORKERS": str(args.workers),
        "CELERY_LOG_LEVEL": "INFO",
        "CELERY_WORKER_CONCURRENCY": str(args.concurrency),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare a native Mhami installation.")
    parser.add_argument("--mode", choices=("central", "standalone"), required=True)
    parser.add_argument("--hostname")
    parser.add_argument("--env-file", type=Path, required=True)
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--postgres-host", default="127.0.0.1")
    parser.add_argument("--postgres-port", type=int, default=5432)
    parser.add_argument("--postgres-db", default="platform")
    parser.add_argument("--postgres-user", default="platform")
    parser.add_argument("--postgres-password")
    parser.add_argument("--redis-url", default="redis://127.0.0.1:6379/0")
    parser.add_argument("--backup-external-uri")
    parser.add_argument("--workers", type=int, default=3)
    parser.add_argument("--concurrency", type=int, default=2)
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.mode == "standalone" and args.hostname not in (None, "", "localhost", "127.0.0.1"):
        print("Standalone mode should use localhost or an explicitly trusted LAN hostname.", file=sys.stderr)
    try:
        values = build_values(args)
        args.data_root.mkdir(parents=True, exist_ok=True)
        _write_env(args.env_file, values, force=args.force)
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"Installer failed: {exc}", file=sys.stderr)
        return 1
    print(f"Environment prepared for {args.mode} mode: {args.env_file}")
    print("Next: install PostgreSQL/Redis, run manage.py upgrade, then register services.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
