# Generated by Django 5.2.17 on 2026-08-30 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0002_supportauthorization_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userbranchmembership',
            name='organization_one_active_branch_per_user',
        ),
        migrations.AddConstraint(
            model_name='userbranchmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user', 'branch'), name='organization_one_active_branch_per_user'),
        ),
    ]
