# Generated by Django 5.2 on 2026-08-25 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('totp', 'TOTP'), ('passkey', 'Passkey')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('credential_id', models.CharField(blank=True, max_length=255)),
                ('public_key', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'method_type', 'active'], name='identity_mf_user_id_09ab1e_idx')],
            },
        ),
    ]
