# Generated by Django 5.2.17 on 2026-08-26 23:49

import apps.identity.fields
from django.db import migrations


def encrypt_existing_mfa_secrets(apps, schema_editor):
    # The backup_restore database is intentionally a narrow restore target and
    # does not contain identity tables. This historical data migration belongs
    # only to the primary application database.
    if schema_editor.connection.alias != "default":
        return
    enrollment_model = apps.get_model("identity", "MfaEnrollment")
    enrollments = enrollment_model.objects.exclude(secret="").only("id", "secret")
    for enrollment in enrollments.iterator():
        enrollment.save(update_fields=["secret"])


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_mfaenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfaenrollment',
            name='secret',
            field=apps.identity.fields.EncryptedSecretField(blank=True, max_length=512),
        ),
        migrations.RunPython(encrypt_existing_mfa_secrets, migrations.RunPython.noop),
    ]
