# Generated by Django 5.2.17 on 2026-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_mfaenrollment_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfaenrollment',
            name='last_used_timestep',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
