# Generated by Django 5.2.17 on 2026-09-29 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_remove_mfa_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='login_id may only contain alphanumeric characters, _, -, and .', regex='^[a-zA-Z0-9_.-]+$')]),
        ),
    ]
